name: Build Jaskar

on:
  push:
    branches: [ '*' ]
    paths-ignore: ['**.md']
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout project
    
      - uses: actions/setup-java@v4
        name: Set up JDK 11
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
        
      - name: Build with Maven
        run: mvn -B package --file pom.xml     
